---
name: ci

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "**/README.md"
      - "**/.env"
  pull_request:
    branches:
      - master
      - dev

  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.16.9
  JAVA_VERSION: 11
  DISTRIBUTION: zulu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter pub get
      - run: touch .env
      - run: flutter analyze .
      - run: flutter test
      - run: rm -rf .env
