name: linter

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'dev'

  workflow_dispatch:

jobs:
  linter:
    if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ANSIBLE: false
          VALIDATE_DART: false
          VALIDATE_GO: false
          VALIDATE_COFFEE: false
          VALIDATE_RUBY: false
          VALIDATE_PYTHON: false
          VALIDATE_PERL: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          FILTER_REGEX_EXCLUDE: (.*ios/Podfile.*|.*google-services.json.*|.*firebase_options.dart.*|.*GoogleService-Info.plist.*)